/*
 * File: main/main.c
 *
 * Created on: 2025-06-15
 * Edited on:  2025-06-16
 * 
 * Version: v8.0.6
 *  
 * Author: Generated by ChatGPT
 */

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"
#include "nvs_flash.h"
#include "esp_event.h"
#include "esp_netif.h"
#include "esp_wifi.h"
#include "esp_http_server.h"

#include "app_logic.h"
#include "wifi_manager.h"
#include "board_manager.h"
#include "mqtt_manager.h"

static const char *TAG = "DCM1";

// Handler must be a C function, not a C++ lambda
static esp_err_t ping_handler(httpd_req_t *req)
{
    const char resp[] = "pong";
    httpd_resp_send(req, resp, sizeof(resp) - 1);
    return ESP_OK;
}

static httpd_handle_t start_http_server(void)
{
    httpd_config_t config = HTTPD_DEFAULT_CONFIG();
    httpd_handle_t server = NULL;

    ESP_LOGI(TAG, "[1] Starting HTTP server...");
    if (httpd_start(&server, &config) != ESP_OK) {
        ESP_LOGE(TAG, "[!] Failed to start HTTP server");
        return NULL;
    }
    ESP_LOGI(TAG, "[2] HTTP server started, handle=%p", (void*)server);

    // Register a simple URI handler for testing
    httpd_uri_t ping_uri = {
        .uri      = "/ping",
        .method   = HTTP_GET,
        .handler  = ping_handler,
        .user_ctx = NULL
    };
    httpd_register_uri_handler(server, &ping_uri);
    ESP_LOGI(TAG, "[3] Registered /ping handler");

    return server;
}

void app_main(void)
{
    ESP_LOGI(TAG, ">> DCM-1 v8.0.6 booting...");

    // 1. Initialize NVS
    ESP_LOGI(TAG, "[1] nvs_flash_init()");
    ESP_ERROR_CHECK(nvs_flash_init());

    // 2. Initialize TCP/IP stack & event loop
    ESP_LOGI(TAG, "[2] esp_netif_init() && esp_event_loop_create_default()");
    ESP_ERROR_CHECK(esp_netif_init());
    ESP_ERROR_CHECK(esp_event_loop_create_default());

    // 3. Board-specific init
    ESP_LOGI(TAG, "[3] board_manager_init()");
    board_manager_init();

    // 4. Application logic setup
    ESP_LOGI(TAG, "[4] app_logic_init()");
    app_logic_init();

    // 5. Wi-Fi manager init + provisioning/connect logic
    ESP_LOGI(TAG, "[5] wifi_manager_init()");
    ESP_ERROR_CHECK(wifi_manager_init());

    if (!wifi_manager_has_saved_credentials()) {
        ESP_LOGW(TAG, "[6] No saved credentials -- provisioning mode");
        wifi_manager_start_provisioning();
    } else {
        ESP_LOGI(TAG, "[6] Found credentials -- connecting to AP");
        wifi_manager_connect();
    }

    // 6. Wait until Wi-Fi is up
    ESP_LOGI(TAG, "[7] Waiting for Wi-Fi ready...");
    while (!wifi_manager_is_ready()) {
        vTaskDelay(pdMS_TO_TICKS(500));
        ESP_LOGI(TAG, "[7] still waiting...");
    }

    ESP_LOGI(TAG, "[8] Wi-Fi ready (mode=%s)",
             wifi_manager_is_sta_connected() ? "STA" : "AP");

    // 7. Start HTTP server
    httpd_handle_t server = start_http_server();
    if (!server) {
        ESP_LOGE(TAG, "[!] HTTP server failed to start");
    }

    // 8. Heartbeat loop
    for (;;) {
        ESP_LOGI(TAG, "[9] Heartbeat @ %u ms",
                 (unsigned int)xTaskGetTickCount());
        vTaskDelay(pdMS_TO_TICKS(5000));
    }
}
